language: go

go: 1.4

before_install:
  - mkdir -p $HOME/gopath/src/sourcegraph.com/sourcegraph
  - mv $TRAVIS_BUILD_DIR $HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-go
  - export TRAVIS_BUILD_DIR=$HOME/gopath/src/sourcegraph.com/sourcegraph/srclib-go
  - cd $TRAVIS_BUILD_DIR
  - export PATH=$PATH:$HOME/gopath/bin
  - export GOBIN=$HOME/gopath/bin

install:
  - sudo wget -NO /tmp/src.zip 'https://api.equinox.io/1/Applications/ap_BQxVz1iWMxmjQnbVGd85V58qz6/Updates/Asset/src-0.0.28.zip?os=linux&arch=amd64&channel=stable'
  - sudo unzip /tmp/src*.zip -d /usr/local/bin
  - sudo mv /usr/local/bin/src-* /usr/local/bin/src
  - sudo chmod +x /usr/local/bin/src
  - src toolchain add sourcegraph.com/sourcegraph/srclib-docker
  - make

script:
  - godep go test ./...
  - src test -m program
